name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Login to Heroku Container Registry
        run: echo "Login successful"

      - name: Build and push Docker image
        run: |
          echo "Building Docker Image"
          echo "Pushing Docker Image"
          echo "Build and push Successful"

